name: Reviung5

on:
  push:
    branches:
      - main
    paths:
      - "**reviung5.*"
  pull_request:
  workflow_dispatch:

jobs:
  build_reviung5:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit
    with:
      build_matrix_path: "build_matrix/reviung5.yaml"
      archive_name: "zmk_reviung5"
