name: Sweep

on:
  push:
    branches:
      - main
    paths:
      - "**sweep.yaml"
      - "**cradio.*"
      - "**34.dtsi"
  pull_request:
  workflow_dispatch:

jobs:
  build_sweep:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    secrets: inherit
    with:
      build_matrix_path: "build_matrix/sweep.yaml"
      archive_name: "zmk_sweep-${{ github.run_number }}"
